name: fortune_wheel
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  audioplayers: ^0.20.1
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/apple.png
    - assets/carrot.png
    - assets/cheese.png
    - assets/fruit.png
    - assets/grapes.png
    - assets/milk.png
    - assets/raspberry.png
    - assets/salad.png

flutter_icons:
  image_path: "assets/dollar.png"
  android: true
  ios: false
  adaptive_icon_background: "#41237A"
  adaptive_icon_foreground: "assets/dollar.png"
